@startuml

enum Roles {
	tutor: TUTOR
	tutelle: TUTELLE
	tutelle: ADMIN
	lambda:	LAMBDA
}

class User {
	_id		:	ID

	firstname	:	String
	lastname	:	String

	password	:	String

	role		:	Roles

	email		:	String

	birthDate	:	Date

	phone		:	string

	address		:	AddressSchema
}

User::role -> Roles

@enduml
